#For the provider URL: Use https://token.actions.githubusercontent.com
#For the "Audience": Use sts.amazonaws.com 
name: Test tagging
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/2 * * * *'
    # inputs:
    #   deploy_to_production:
    #     description: "Deploy to production environment?"
    #     default: "false"
    #     required: true
    #     type: choice
    #     options:
    #       - 'true'
    #       - 'false'
env:
  AWS_REGION : "us-east-1"
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  npm-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set TEMP Environment Variable
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TEMP=${{ secrets.PR_SECRET }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "schedule" ]; then
            echo "TEMP=${{ secrets.SCHEDULE_SECRET }}" >> $GITHUB_ENV
          fi
      
      - name: Print TEMP
        run: |
          if [ $ENV_VAR == "24t3df" ]; then
            echo "PR_SECRET"
          elif [ $ENV_VAR == "a9yxci" ]; then
            echo "SCHEDULE_SECRET"
          fi
          echo $ENV_VAR
        env:
          ENV_VAR: ${{ env.TEMP }}
