#For the provider URL: Use https://token.actions.githubusercontent.com
#For the "Audience": Use sts.amazonaws.com 
name: Test if
on:
  workflow_dispatch:
    inputs:
      deploy_to_production:
        description: "Deploy to production environment?"
        default: "false"
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
env:
  AWS_REGION : "us-east-1"
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  npm-build-push:
    runs-on: ubuntu-latest
    steps:
      # Update build artifacts on production environment
      # Export timestamp and branch name to environment variables
      - name: Export env variables
        run: |
          echo "TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "Workflow_Executor=${{ github.actor }}" >> $GITHUB_ENV
          echo "Value = ${{ env.Workflow_Executor }}"

      # Get ephemeral AWS credentials
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::325487104949:role/Giverbox-Github-OIDC-S3-Role
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      # Print creds
      - name: print ephemeral creds
        run: |
          echo $AWS_ACCESS_KEY_ID
