#For the provider URL: Use https://token.actions.githubusercontent.com
#For the "Audience": Use sts.amazonaws.com 
name: Test Branch Name
on:
  push:
    branches:
      - publish

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      # Install node v16.20.2
      - name: Print branch
        run: |
          echo "${{ github.ref.GITHUB_REF_NAME }}"

      # checkout repository with brnach selected for branch_name
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref.GITHUB_REF_NAME }}
          
      - name: Print directory content
        run: |
          ls -la
          
      - name: Send payload file to slack
        id: slack
        continue-on-error: true
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Link-checker build result: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<!here> Link-checker build result: *${{ job.status }}*\n Please check the <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build URL> for logs and linkchecker report."
                  }
                }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
